### PR TITLE
reusabilty

### PR DESCRIPTION
**Pull request by p1tz**
Hi,

removed the static keyword from maps in the Discoverer class. If one creates multiple instances of, say, the ClasspathDiscoverer with different listeners, classes are discovered multiple times.

cheers

### CODE REVIEW

**Comment by georgeOsdDev** [comment]
@p1tz 
Thanks.
Do you want me to release a new version immediately?

**Comment by p1tz** [comment]
thank you for your quick response :)

if it's not too much of a hassle, yes please.

**Comment by ngocdaothanh** [comment]
Hi,

If you use Scala, don't forget to check out Sclasner:
https://github.com/ngocdaothanh/sclasner

**Comment by georgeOsdDev** [comment]
Hi

I released 1.4 to sonatype.
https://oss.sonatype.org/index.html#nexus-search;quick~annovention

It will be released to maven central in few hour automatically.

**Comment by p1tz** [comment]
thank you very much!

(I'm using scala only occasionally, write-once-throw-away)

**Pull request merged**
