### PR TITLE
Added new series of listeners that publish the Javassist objects to

### PR DESCRIPTION
**Pull request by dbennett455**
subscribers.  The Discoverer class was ammended to accept and send to
the new listeners in addition to the original String listeners.

### CODE REVIEW

**Comment by ngocdaothanh** [comment]
Thanks, I've merged.

Can you update README to explain about the new feature that you added? Ex: Add info to the section "Difference compared to the original Annovention library" in README etc., what ever you think appropriate.

I'll release a new version, so that you can easily use new the new feature in your apps.

**Comment by dbennett455** [comment]
Thank Ngoc,

I will update the README.   I am also working on support for parameter
annotations as I need this for a JAX-RS related project. 

--Dave

**Comment by dbennett455** [comment]
Updated README for your approval.  I am also working on new listeners
for parameter annotations.

**Comment by ngocdaothanh** [comment]
I've released v1.5 to Sonatype:
http://oss.sonatype.org/content/repositories/releases/tv/cntt/annovention/1.5/

It should be mirrored to Maven Central within a few hours.

**Pull request merged**
